/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ezeventparkingclient;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.InputStreamReader;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 *
 * @author Nico
 */
public class formEvent extends javax.swing.JFrame {

    Socket clientSocket;
    BufferedReader msgFromServer;
    DataOutputStream msgToServer;
    public String userID;
    public String eventID;

    /**
     * Creates new form formOrderEvent
     */
    public formEvent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        labelEvent1 = new javax.swing.JLabel();
        labelNama2 = new javax.swing.JLabel();
        labelNama3 = new javax.swing.JLabel();
        labelTiket1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labelEvent = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelNama1 = new javax.swing.JLabel();
        labelTiket = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        labelEvent2 = new javax.swing.JLabel();
        labelNama4 = new javax.swing.JLabel();
        labelNama5 = new javax.swing.JLabel();
        labelTiket2 = new javax.swing.JLabel();
        btnReserve = new javax.swing.JButton();
        labelbiasa2 = new javax.swing.JLabel();
        labelbiasa3 = new javax.swing.JLabel();
        labelLokasi = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        labelNamaEvent = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jPanel6.setLayout(null);
        jPanel5.add(jPanel6);
        jPanel6.setBounds(0, 0, 0, 0);

        jPanel7.setBackground(new java.awt.Color(0, 153, 255));

        labelEvent1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        labelEvent1.setForeground(new java.awt.Color(0, 0, 0));
        labelEvent1.setText("Event");
        labelEvent1.setToolTipText("");

        labelNama2.setForeground(new java.awt.Color(0, 0, 0));
        labelNama2.setText("SIGMA");
        labelNama2.setToolTipText("");

        labelNama3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNama3.setForeground(new java.awt.Color(0, 0, 0));
        labelNama3.setText("EZEVENT");
        labelNama3.setToolTipText("");

        labelTiket1.setForeground(new java.awt.Color(0, 0, 0));
        labelTiket1.setText("Tiket");
        labelTiket1.setToolTipText("");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(labelNama3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 551, Short.MAX_VALUE)
                .addComponent(labelTiket1)
                .addGap(33, 33, 33)
                .addComponent(labelEvent1)
                .addGap(33, 33, 33)
                .addComponent(labelNama2)
                .addGap(50, 50, 50))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEvent1)
                    .addComponent(labelNama2)
                    .addComponent(labelNama3)
                    .addComponent(labelTiket1))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel7);
        jPanel7.setBounds(0, 0, 900, 70);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Hai kamu mau cari event apa ?");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(300, 120, 330, 50);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel8);
        jPanel8.setBounds(40, 190, 820, 260);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("More...");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(440, 490, 50, 20);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 0, 0);

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));

        labelEvent.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        labelEvent.setForeground(new java.awt.Color(0, 0, 0));
        labelEvent.setText("Event");
        labelEvent.setToolTipText("");

        labelNama.setForeground(new java.awt.Color(0, 0, 0));
        labelNama.setText("SIGMA");
        labelNama.setToolTipText("");

        labelNama1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNama1.setForeground(new java.awt.Color(0, 0, 0));
        labelNama1.setText("EZEVENT");
        labelNama1.setToolTipText("");

        labelTiket.setForeground(new java.awt.Color(0, 0, 0));
        labelTiket.setText("Tiket");
        labelTiket.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(labelNama1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 567, Short.MAX_VALUE)
                .addComponent(labelTiket)
                .addGap(33, 33, 33)
                .addComponent(labelEvent)
                .addGap(33, 33, 33)
                .addComponent(labelNama)
                .addGap(50, 50, 50))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEvent)
                    .addComponent(labelNama)
                    .addComponent(labelNama1)
                    .addComponent(labelTiket))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 900, 70);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Hai kamu mau cari event apa ?");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(300, 120, 330, 50);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(40, 190, 820, 260);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("More...");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(440, 490, 50, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 0);

        jPanel9.setBackground(new java.awt.Color(229, 237, 252));
        jPanel9.setLayout(null);

        jPanel10.setBackground(new java.awt.Color(0, 153, 255));

        labelEvent2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        labelEvent2.setForeground(new java.awt.Color(0, 0, 0));
        labelEvent2.setText("Event");
        labelEvent2.setToolTipText("");

        labelNama4.setForeground(new java.awt.Color(0, 0, 0));
        labelNama4.setText("SIGMA");
        labelNama4.setToolTipText("");

        labelNama5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNama5.setForeground(new java.awt.Color(0, 0, 0));
        labelNama5.setText("EZEVENT");
        labelNama5.setToolTipText("");

        labelTiket2.setForeground(new java.awt.Color(0, 0, 0));
        labelTiket2.setText("Tiket");
        labelTiket2.setToolTipText("");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(labelNama5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 357, Short.MAX_VALUE)
                .addComponent(labelTiket2)
                .addGap(33, 33, 33)
                .addComponent(labelEvent2)
                .addGap(33, 33, 33)
                .addComponent(labelNama4)
                .addGap(50, 50, 50))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEvent2)
                    .addComponent(labelNama4)
                    .addComponent(labelNama5)
                    .addComponent(labelTiket2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel10);
        jPanel10.setBounds(0, 0, 690, 70);

        btnReserve.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReserve.setText("Reservasi Ticket");
        btnReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveActionPerformed(evt);
            }
        });
        jPanel9.add(btnReserve);
        btnReserve.setBounds(470, 320, 139, 30);

        labelbiasa2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelbiasa2.setForeground(new java.awt.Color(0, 0, 0));
        labelbiasa2.setText("Tanggal:");
        jPanel9.add(labelbiasa2);
        labelbiasa2.setBounds(470, 150, 110, 20);

        labelbiasa3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelbiasa3.setForeground(new java.awt.Color(0, 0, 0));
        labelbiasa3.setText("Lokasi:");
        jPanel9.add(labelbiasa3);
        labelbiasa3.setBounds(470, 130, 110, 20);

        labelLokasi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelLokasi.setForeground(new java.awt.Color(0, 0, 0));
        labelLokasi.setText("LOKASI");
        jPanel9.add(labelLokasi);
        labelLokasi.setBounds(580, 130, 110, 20);

        labelDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDate.setForeground(new java.awt.Color(0, 0, 0));
        labelDate.setText("DATE");
        jPanel9.add(labelDate);
        labelDate.setBounds(580, 150, 110, 20);

        labelNamaEvent.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelNamaEvent.setForeground(new java.awt.Color(0, 0, 0));
        labelNamaEvent.setText("--nama acara--");
        jPanel9.add(labelNamaEvent);
        labelNamaEvent.setBounds(34, 88, 446, 47);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("--deskripsi--");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setAutoscrolls(true);
        jPanel9.add(jLabel5);
        jLabel5.setBounds(30, 140, 410, 230);

        getContentPane().add(jPanel9);
        jPanel9.setBounds(0, 0, 690, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveActionPerformed
        // TODO add your handling code here:
        try {
            clientSocket = new Socket("localhost", 6000);
            String event = labelNamaEvent.getText();
            String msg = "eventreservation/buyeventreservation/" + userID + "/" + event + "/" + labelDate.getText() + " 00:00:00.0" + "\n";
            sendMessage(msg);

            String respond = getMessage();
            JOptionPane.showMessageDialog(this, respond);
            this.dispose();

        } catch (Exception ex) {
            System.out.println("Error di formEvent");
        }
    }//GEN-LAST:event_btnReserveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formEvent().setVisible(true);
            }
        });
    }

    public void sendMessage(String s) {
        try {
            msgToServer = new DataOutputStream(clientSocket.getOutputStream());
            msgToServer.writeBytes(s + "\n");
        } catch (Exception e) {
        }
    }

    public String getMessage() {
        String chatServer = "";
        try {
            msgFromServer = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
            chatServer = msgFromServer.readLine();
        } catch (Exception ex) {
        }
        return chatServer;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReserve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelEvent;
    private javax.swing.JLabel labelEvent1;
    private javax.swing.JLabel labelEvent2;
    private javax.swing.JLabel labelLokasi;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNama1;
    private javax.swing.JLabel labelNama2;
    private javax.swing.JLabel labelNama3;
    private javax.swing.JLabel labelNama4;
    private javax.swing.JLabel labelNama5;
    private javax.swing.JLabel labelNamaEvent;
    private javax.swing.JLabel labelTiket;
    private javax.swing.JLabel labelTiket1;
    private javax.swing.JLabel labelTiket2;
    private javax.swing.JLabel labelbiasa2;
    private javax.swing.JLabel labelbiasa3;
    // End of variables declaration//GEN-END:variables
}
