/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ezeventparkingclient;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.InputStreamReader;
import java.net.Socket;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author Nico
 */
public class formMenuEvent extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    Socket clientSocket;
    BufferedReader msgFromServer;
    DataOutputStream msgToServer;
    public String userID;
    ArrayList<String> listIndexLocation = new ArrayList<>();
    
    public formMenuEvent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labelEvent = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelNama1 = new javax.swing.JLabel();
        labelTiket = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblNamaEvent = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        lblLokasi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDeskripsi1 = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        lblNamaEvent1 = new javax.swing.JLabel();
        lblTanggal1 = new javax.swing.JLabel();
        lblHarga1 = new javax.swing.JLabel();
        lblLokasi1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textDeskripsi2 = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        lblNamaEvent2 = new javax.swing.JLabel();
        lblTanggal2 = new javax.swing.JLabel();
        lblHarga2 = new javax.swing.JLabel();
        lblLokasi2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textDeskripsi3 = new javax.swing.JTextArea();

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(229, 237, 252));
        jPanel1.setLayout(null);

        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 0, 0);

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));

        labelEvent.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        labelEvent.setForeground(new java.awt.Color(0, 0, 0));
        labelEvent.setText("Event");
        labelEvent.setToolTipText("");

        labelNama.setForeground(new java.awt.Color(0, 0, 0));
        labelNama.setText("SIGMA");
        labelNama.setToolTipText("");

        labelNama1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNama1.setForeground(new java.awt.Color(0, 0, 0));
        labelNama1.setText("EZEVENT");
        labelNama1.setToolTipText("");

        labelTiket.setForeground(new java.awt.Color(0, 0, 0));
        labelTiket.setText("Tiket");
        labelTiket.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(labelNama1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 551, Short.MAX_VALUE)
                .addComponent(labelTiket)
                .addGap(33, 33, 33)
                .addComponent(labelEvent)
                .addGap(33, 33, 33)
                .addComponent(labelNama)
                .addGap(50, 50, 50))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEvent)
                    .addComponent(labelNama)
                    .addComponent(labelNama1)
                    .addComponent(labelTiket))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 900, 70);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Hai ! Hari ini kamu mau cari event apa ?");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(250, 120, 430, 50);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("More...");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(440, 500, 50, 20);

        jPanel6.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNamaEvent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNamaEvent.setForeground(new java.awt.Color(0, 0, 0));
        lblNamaEvent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNamaEvent.setText("--Nama Event--");
        lblNamaEvent.setAlignmentX(0.5F);
        jPanel5.add(lblNamaEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 26, 203, -1));

        lblTanggal.setForeground(new java.awt.Color(0, 0, 0));
        lblTanggal.setText("--tanggal--");
        jPanel5.add(lblTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 63, 180, -1));

        lblHarga.setForeground(new java.awt.Color(0, 0, 0));
        lblHarga.setText("--harga--");
        jPanel5.add(lblHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 82, -1, -1));

        lblLokasi.setForeground(new java.awt.Color(0, 0, 0));
        lblLokasi.setText("--lokasi--");
        jPanel5.add(lblLokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 104, -1, -1));

        textDeskripsi1.setBackground(new java.awt.Color(255, 255, 255));
        textDeskripsi1.setColumns(20);
        textDeskripsi1.setRows(5);
        jScrollPane1.setViewportView(textDeskripsi1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 180, -1));

        jPanel6.add(jPanel5);
        jPanel5.setBounds(50, 20, 203, 244);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNamaEvent1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNamaEvent1.setForeground(new java.awt.Color(0, 0, 0));
        lblNamaEvent1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNamaEvent1.setText("--Nama Event--");
        jPanel9.add(lblNamaEvent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 26, 203, -1));

        lblTanggal1.setForeground(new java.awt.Color(0, 0, 0));
        lblTanggal1.setText("--tanggal--");
        jPanel9.add(lblTanggal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 63, 180, -1));

        lblHarga1.setForeground(new java.awt.Color(0, 0, 0));
        lblHarga1.setText("--harga--");
        jPanel9.add(lblHarga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 81, -1, -1));

        lblLokasi1.setForeground(new java.awt.Color(0, 0, 0));
        lblLokasi1.setText("--lokasi--");
        jPanel9.add(lblLokasi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 103, -1, -1));

        textDeskripsi2.setBackground(new java.awt.Color(255, 255, 255));
        textDeskripsi2.setColumns(20);
        textDeskripsi2.setRows(5);
        jScrollPane2.setViewportView(textDeskripsi2);

        jPanel9.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 180, -1));

        jPanel6.add(jPanel9);
        jPanel9.setBounds(290, 20, 203, 244);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNamaEvent2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNamaEvent2.setForeground(new java.awt.Color(0, 0, 0));
        lblNamaEvent2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNamaEvent2.setText("--Nama Event--");
        jPanel10.add(lblNamaEvent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 26, 203, -1));

        lblTanggal2.setForeground(new java.awt.Color(0, 0, 0));
        lblTanggal2.setText("--tanggal--");
        jPanel10.add(lblTanggal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 63, 180, -1));

        lblHarga2.setForeground(new java.awt.Color(0, 0, 0));
        lblHarga2.setText("--harga--");
        jPanel10.add(lblHarga2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 82, -1, -1));

        lblLokasi2.setForeground(new java.awt.Color(0, 0, 0));
        lblLokasi2.setText("--lokasi--");
        jPanel10.add(lblLokasi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 104, -1, -1));

        textDeskripsi3.setBackground(new java.awt.Color(255, 255, 255));
        textDeskripsi3.setColumns(20);
        textDeskripsi3.setRows(5);
        jScrollPane3.setViewportView(textDeskripsi3);

        jPanel10.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 180, -1));

        jPanel6.add(jPanel10);
        jPanel10.setBounds(530, 20, 203, 244);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(50, 190, 800, 290);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        formMenuSelection frm = new formMenuSelection();
        frm.userID = userID;
        frm.labelNama.setText(labelNama.getText());
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        clientSocket = SocketManager.getInstance().getClientSocket();
        // new Socket("ipaddress", 12345);
        System.out.println(userID);
        String msg = "event/getallevent/" + userID + "\n";

        sendMessage(msg);

        String response = getMessage();

        ArrayList<String> splitResponse = new ArrayList<>(Arrays.asList(response.split("/")));
        if (splitResponse.get(0).equals("SUCCESS")) {
                splitResponse.remove(0);
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.S");
                
                String[] dataEvent1 = splitResponse.get(0).split(";");
                lblNamaEvent.setText(dataEvent1[1]);
                LocalDateTime dateTime1 = LocalDateTime.parse(dataEvent1[6], formatter);
                 // Membuat formatter untuk output yang diinginkan tanpa "T"
                DateTimeFormatter outputFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

                // Mengonversi kembali objek LocalDateTime ke string dengan format yang diinginkan
                String formattedDate1 = dateTime1.format(outputFormatter);
                lblTanggal.setText("Date: " + formattedDate1);
                lblHarga.setText("Price: Rp." + (int)Double.parseDouble(dataEvent1[5]));
                lblLokasi.setText("Location: " + dataEvent1[4]);
                textDeskripsi1.setText(dataEvent1[2]);
                
                String[] dataEvent2 = splitResponse.get(1).split(";");
                lblNamaEvent1.setText(dataEvent2[1]);
                LocalDateTime dateTime2 = LocalDateTime.parse(dataEvent2[6], formatter);
                lblTanggal1.setText("Date: " + dateTime2);
                lblHarga1.setText("Price: Rp." + (int)Double.parseDouble(dataEvent2[5]));
                lblLokasi1.setText("Location: " + dataEvent2[4]);
                textDeskripsi2.setText(dataEvent2[2]);
                
                String[] dataEvent3 = splitResponse.get(2).split(";");
                lblNamaEvent2.setText(dataEvent3[1]);
                LocalDateTime dateTime3 = LocalDateTime.parse(dataEvent3[6], formatter);
                lblTanggal2.setText("Date: " + dataEvent3[6]);
                lblHarga2.setText("Price: Rp." + (int)Double.parseDouble(dataEvent3[5]));
                lblLokasi2.setText("Location: " + dataEvent3[4]);
                textDeskripsi3.setText(dataEvent3[2]);
            }
    }//GEN-LAST:event_formWindowOpened
    public void sendMessage(String s) {
        try {
            msgToServer = new DataOutputStream(clientSocket.getOutputStream());
            msgToServer.writeBytes(s);

        } catch (Exception e) {
        }
    }

    public String getMessage() {
        String chatServer = "";
        try {
            msgFromServer = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
            chatServer = msgFromServer.readLine();
        } catch (Exception ex) {
        }

        return chatServer;

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formMenuEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formMenuEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formMenuEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formMenuEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formMenuEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelEvent;
    public javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNama1;
    private javax.swing.JLabel labelTiket;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblHarga1;
    private javax.swing.JLabel lblHarga2;
    private javax.swing.JLabel lblLokasi;
    private javax.swing.JLabel lblLokasi1;
    private javax.swing.JLabel lblLokasi2;
    private javax.swing.JLabel lblNamaEvent;
    private javax.swing.JLabel lblNamaEvent1;
    private javax.swing.JLabel lblNamaEvent2;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblTanggal1;
    private javax.swing.JLabel lblTanggal2;
    private javax.swing.JTextArea textDeskripsi1;
    private javax.swing.JTextArea textDeskripsi2;
    private javax.swing.JTextArea textDeskripsi3;
    // End of variables declaration//GEN-END:variables
}
